FROM golang:1.16-alpine3.12 as goBuilder
ADD ./ /lu-short
WORKDIR /lu-short
RUN export CGO_ENABLED=0 && export GOPROXY=https://goproxy.io,direct && go build -v -o lu-short

FROM alpine:3.12
MAINTAINER lico
RUN apk update && apk add curl bash tree tzdata \
    && cp -r -f /usr/share/zoneinfo/Hongkong /etc/localtime
COPY --from=goBuilder /lu-short/lu-short /
RUN chmod u+x /lu-short
EXPOSE 80
CMD ["/lu-short"]
